### ISSUE TITLE
Create strings from allocated memory

### ISSUE THREAD

**Issue by herwinw** [seven1m/tm#10]
Kind of a vague title, but I'm talking about cases like this (simplified version of `IoObject::read`:
```c++
char *buf = new char[count + 1];
bytes_read = ::read(m_fileno, buf, count);
String result { buf, static_cast<size_t>(bytes_read) };
delete[] buf;
return result;
```
And the String internals create a new buffer inside of the String, copies the memory out of the old buffer into the new one. This feels like one memory allocation too many. It would be nice if w were able to prevent that.
Since raw pointers don't indicate any kind of ownership, we need a different method of constructing this.

The easiest is probably to create a new constructor, like `static String::consume_charp(const char* buf, const size_t size)`, which simply copies the pointer and the size into a new String object. A possible alternative to this would be to add a third argument to the constructor to indicate that the String can take ownership of the data (`String(const char *str, const size_t length, const bool take_ownership = false)`
A different approach would be to indicate the ownership in the argument. We would have to step away from raw pointers and wrap it into something that indicates ownership. A unique_ptr/owned_ptr would sound logical, but that would need some updates to support array allocation and deallocation.
A different approach would be to make the `c_str` method non-const, so you can simply use that instead of the buffer. This is how `std::string` works:
```c++
TM::String buf { count, '\0' }; // no need for the `+1` anymore
bytes_read = ::read(m_fileno, buf.c_str(), count);
return buf; // or std::move buf into a StringObject
```

And even though this case only mentions String, the same issue can be found in Vector.

**Comment by herwinw** [comment]
It turns out you can work around that last issue by taking the address of the first character:
```c++
TM::String buf { count, '\0' };
bytes_read = ::read(m_fileno, &buf[0], count);
buf.truncate(bytes_read);
return buf;
```

**Comment by seven1m** [comment]
A new constructor that takes ownership of the char* makes sense to me.
